services:
  - docker

env:
  global:
    # GPG_KEY_PASSPHRASE:
    - secure: "iT+68YhJqPhlG0KR3GrNUlKf2pCaH4Hm4+4lY2byhlfeN3gakRPUBdfDjn6xzyziBXSLwj6EjUzZmMxCUQQGaENAhF3hrFtMRRFVOoLf3O4Uv8qMiIzk3Y7ULPRJPZzaqafW1a9K3LFNSHm47Wf2Wsf9rfO0dmatFkbsTMlJvb/FkbQWbqdDM7kxNNcpMQUmiFZ+j+sjWlabH+rc9Hi/uOjg95hHW4YWu4f43ROKzfaWX+75URAQ8Ih2Tw/oHNkvwMlOlVd9Csb5T3fvmTGBvdAPntLIdN/Iz7rionzMP3EUm2tC49A1PNRxLAEF4zNim9cHCbHGNpJnnWsPux9N128s+i1KMFtxZR5tBqSbX/gO2CN+SQJiSUvMx2Zu7NgRwsz1tYD8667i65//ZtrQbAvaSjxOSav0Q6Cdz/PlCWbfOmActwRxdEdrt+CtYnh2XyBmzLySDFqEjRCa5zedJrMJ2WbAxxmL/UgyMRYLbOEk5/7NR2q7ZX3FCWj+FJdQbRxayJ/6cltB4DYAXqdHv1hpWVgQGTfUkhiHunAuZygOl44pLeEWi4j6ETB8xzgscgcO0wzjToHcpnWQvDBnpkm26uCaR8jcn2ObEbBci1QdaRch9PfV81YIAL9Ssay/WQktGE/Ewe0Gm2DOcU0YWvU3BJixL50Wc1UBYGt+Xxw="
    - GPG_KEY_ID=6382A4D7
    - OSSRH_USERNAME=qUS14DjF
    # OSSRH_PASSWORD:
    - secure: "ULU6IcHGK2oDfFdQ3uldt+6yowo49PYQePY2wXQDxn6QGIVJG321kbBB5dtHT2o8R/xJZszc6wX/a+jtMU83Vi/LJ1ojBjOODkZAiLyoJlw2dPBgQVT9U3hWxtm8bBgKhPmQvwCbrcuFu8eVueRA7siz7M/upZsNWDBt0M5AOtV4a0tRwCthiWChpb7fE703g6hEowuLZwbzxPmy9lZj/NFRV8pSyDRTdyTezl0T1vmajzyAk6byLEhHdbtGLZsmgrSJCiTrJ0xS+jmI0WXYzHcvNSNd43Mt5yay+cGAdburiVkhilzpxu09U5tYgIoyNEbLF9szO0MX22fFrvyD9iq9Wt6ksPk8e7h3U/+1P/brJxPZw94HPMhnD1+GW0AGlV+WwUbhsvOohJTzkksNQjIUyKy9Ax1OaHTwhYQa6qllUafFW/Skd9efdhZRdyHY6qCyw/L2Zbs+Bu7bUBWiXkMcGjs6msP/gu52g2pIH2a8hVWKnIVV7XM3JKxQ5KtTD5tTdAo0InCfP7G7/xlPpmE8aCg9DvB8oLALUGRpNxkcol2ZqpYSUH/MApePEJGWMG9pWRQx//GQokHK+EhZqr/qcbrxy3WAd8YuiDEitnrfbKjwvPA44McLTq9R6+PKJBl01KtCa6882XIa2JDeMDKF8hDT5WxRmYhH8knXpCM="

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker --version

  # We can't use an environment variable for this because Travis doesn't support encrypted environment variables large enough to hold it.
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then export GPG_KEY_RING="$(openssl aes-256-cbc -K $encrypted_2ebe366193ee_key -iv $encrypted_2ebe366193ee_iv -in travis/keyring.enc -out /dev/stdout -d)"; fi

script: ./travis/build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: ./batect publishSnapshot
    skip_cleanup: true
    on:
      tags: false
      repo: charleskorn/kaml
      condition: $TRAVIS_BRANCH = "master" # We can't use branch: master here because we're using tags: false (see https://docs.travis-ci.com/user/deployment/#conditional-releases-with-on)

  - provider: script
    script: ./batect publishRelease
    skip_cleanup: true
    on:
      tags: true
      repo: charleskorn/kaml

  - provider: releases
    api_key:
      secure: H+DP0+Xs/B1CJH80NHqWdCuB9gyFfOCNFQ+I2lP7v/oj8SHABg+D41MNu0iUfPPEHjbFa3XmIPG1ij2koHeS6E3L1Vf310Cq4oUsahViMhf7EG9e1bDwiiXq2+/VhJVHNuLmj9INpcA/thepgEeFJqO9A36Zl4kiRYmqu8ghKoKTmLhhBrycVzhZmziUaoXM3VLv2FY+uDQsrB1fQwX7e7QVBJMOcqe0XLyFdaAoVd7mWHMg1AduhWyxy0Jzj+EHxb5IQJPf5qLxogDQ8cyW0JTpRobeCV2qxTpQYwGvAluNm426WDNcFNUu5U9FGMMZJ1UEJLEahi2WnBWe1zJOPln2cmjefNPVT5bdCahEEnFBjlG8+duFr97RCcN9VYy2C5Febv4cuhtJz4DXPwzT3YVdPQC02pBZhclDE/oLNwHAGRjWnPmGWEXrjXDhl7tANLgv3hkkHZZDAvyLReSaDZ9UFb8dL4UygW/XT+8fYaeN30t6Tpaap37T328Hp2df5bqY6bPFqgdRTohMQ8ce5BSm6y8fnvhibkEmkKY9jt+DAyIHEeADq/i0rJmmETAlsCuzRSu2g+bv5gI4sYFzELbgCkgr9EhmlX3V+Canh5C3ncoYA/M5zfRNAKPdTaVkRfwtoEy11fEPNHX7GTN8aVOlMstEN+QfQcCm66+gHMU=
    skip_cleanup: true
    file_glob: true
    file: build/release/*
    on:
      tags: true
      repo: charleskorn/kaml

before_cache:
  - rm -f  .gradle-cache/caches/modules-2/modules-2.lock
  - rm -fr .gradle-cache/caches/*/plugin-resolution/
  - rm -f  .gradle-cache/caches/*/fileHashes/fileHashes.bin
  - rm -f  .gradle-cache/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
    - .gradle-cache/caches/
    - .gradle-cache/wrapper/
